[package]
name = "theseus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "theseus"
crate-type = ["cdylib"]

[dependencies]
ariadne = "0.5.1"
pyo3 = "0.24.0"
